# Generated by Django 5.0.3 on 2024-06-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['completed']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='completed',
        ),
    ]
